
services: docker

branches:
  only:
  - master

script:
  - docker --version # print the version for logging
  - docker-compose --version
  - docker-compose -f udagram-deployment/docker-compose-build.yaml build --parallel

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f udagram-deployment/docker-compose-build.yaml push